# Generated by Django 5.1.7 on 2025-07-15 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rankings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratingchange",
            name="userid",
        ),
        migrations.AddField(
            model_name="ratingchange",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ratingchange",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
