# Generated by Django 5.1.7 on 2025-07-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='pid',
        ),
    ]
