# Generated by Django 5.1.7 on 2025-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_remove_problem_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="samples",
            field=models.TextField(),
        ),
    ]
