# Generated by Django 5.1.7 on 2025-07-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_alter_problem_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="testcases_added",
            field=models.BooleanField(default=False),
        ),
    ]
