# Generated by Django 5.1.7 on 2025-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0006_problem_testcase_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="testcase_zip",
            field=models.FileField(upload_to="problem_testcases/"),
        ),
    ]
