# Generated by Django 5.1.7 on 2025-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0008_remove_problem_testcase_zip_problem_testcases_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="testcases_zip",
            field=models.FileField(upload_to="problem_testcases/"),
        ),
    ]
