# Generated by Django 5.1.7 on 2025-07-19 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0009_alter_problem_testcases_zip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="solution",
        ),
    ]
