# Generated by Django 5.1.7 on 2025-07-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_remove_problem_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='testcases_zip',
            field=models.FileField(blank=True, upload_to='problem_testcases/'),
        ),
    ]
