# Generated by Django 5.1.7 on 2025-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_alter_problem_testcases_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='has_simulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='simulation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
