# Generated by Django 5.1.7 on 2025-07-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rated', models.BooleanField(default=False)),
                ('season', models.IntegerField()),
                ('tjioi', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('editorial', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
