# Generated by Django 5.1.7 on 2025-07-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='editorial',
            field=models.URLField(blank=True, null=True),
        ),
    ]
