# Generated by Django 5.1.7 on 2025-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_contest_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
