# Generated by Django 5.1.7 on 2025-07-07 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.TextField()),
                ('code', models.TextField()),
                ('verdict', models.TextField(default='Running')),
                ('runtime', models.IntegerField(default=-1)),
                ('memory', models.IntegerField(default=-1)),
                ('contest', models.IntegerField(blank=True, null=True)),
                ('problemid', models.IntegerField()),
                ('problemname', models.CharField(blank=True, max_length=255, null=True)),
                ('insight', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
