# Generated by Django 5.1.7 on 2025-07-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0005_alter_submission_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
