# Generated by Django 5.1.7 on 2025-07-13 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runtests", "0006_alter_submission_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"get_latest_by": "timestamp"},
        ),
    ]
