# Generated by Django 5.1.7 on 2025-07-15 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtests", "0007_alter_submission_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
