# Generated by Django 5.1.7 on 2025-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtests", "0008_alter_submission_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(max_length=10),
        ),
    ]
