# Generated by Django 5.1.7 on 2025-08-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0009_alter_submission_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='memory',
        ),
    ]
