# Generated by Django 5.1.7 on 2025-09-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtests', '0010_remove_submission_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.TextField(default='Waiting in Queue'),
        ),
    ]
