# Generated by Django 5.1.7 on 2025-07-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graderuser",
            name="tjioi_user",
            field=models.BooleanField(default=False),
        ),
    ]
