# Generated by Django 5.1.7 on 2025-07-15 21:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_graderuser_author_drops'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderuser',
            name='index',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='graderuser',
            name='inhouse',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='graderuser',
            name='inhouses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=10), default=list, size=None),
        ),
    ]
