# Generated by Django 5.1.7 on 2025-07-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_graderuser_index_graderuser_inhouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderuser',
            name='rank',
            field=models.IntegerField(default=100),
        ),
    ]
