# Generated by Django 5.1.7 on 2025-07-15 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0007_graderuser_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graderuser",
            name="rank",
        ),
    ]
