# Generated by Django 5.1.7 on 2025-07-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0008_remove_graderuser_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="graderuser",
            name="usaco_rating",
            field=models.IntegerField(default=800),
        ),
    ]
