# Generated by Django 5.1.7 on 2025-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0007_alter_problem_testcase_zip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="testcase_zip",
        ),
        migrations.AddField(
            model_name="problem",
            name="testcases_zip",
            field=models.FileField(
                default="default.txt", upload_to="problem_testcases/"
            ),
        ),
    ]
